# Generated by Django 6.0.6 on 2026-07-04 15:14

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0001_search_infrastructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleIndex",
            fields=[
                ("ulid", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("creator", models.TextField(null=True)),
                ("subject_place", models.TextField(null=True)),
                ("ref_code", models.TextField(null=True)),
                ("media_type", models.TextField(null=True)),
                ("document_type", models.TextField(null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("archivist_text", models.TextField(blank=True, default="")),
                ("date_edtf", models.TextField(null=True)),
                ("date_earliest", models.DateField(null=True)),
                ("date_latest", models.DateField(null=True)),
                (
                    "decades",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list
                    ),
                ),
                ("collection_id", models.TextField()),
                (
                    "collection_ancestors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("archivist_only", models.BooleanField()),
                ("tier", models.TextField(null=True)),
                (
                    "groups",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("config_version", models.IntegerField()),
                (
                    "general_tsv",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("title"),
                            models.F("ref_code"),
                            models.F("tags"),
                            models.F("creator"),
                            models.F("subject_place"),
                            models.F("media_type"),
                            models.F("document_type"),
                            models.F("body"),
                            function="bundesarchiv_general_tsv",
                            output_field=django.contrib.postgres.search.SearchVectorField(),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "archivist_tsv",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("archivist_text"),
                            function="bundesarchiv_archivist_tsv",
                            output_field=django.contrib.postgres.search.SearchVectorField(),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["general_tsv"], name="index_general_tsv_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["archivist_tsv"], name="index_archivist_tsv_gin"
                    ),
                    models.Index(fields=["collection_id"], name="index_collection_id_btree"),
                    models.Index(fields=["date_earliest"], name="index_date_earliest_btree"),
                ],
            },
        ),
    ]
