# Generated by Django 6.0.6 on 2026-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_articleindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleindex",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
