# Generated by Django 6.1.1 on 2026-09-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0003_articleindex_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleindex",
            name="added_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name="articleindex",
            index=models.Index(fields=["added_at"], name="index_added_at_btree"),
        ),
    ]
