# Generated by Django 6.1.1 on 2026-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0004_articleindex_added_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleindex",
            name="file_counts",
            field=models.JSONField(default=dict),
        ),
    ]
