# Generated by Django 6.1.1 on 2026-09-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0005_articleindex_file_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleindex",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="articleindex",
            name="deleted_by",
            field=models.TextField(null=True),
        ),
    ]
