# Generated by Django 6.1.1 on 2026-10-06 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0006_articleindex_deleted"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="articleindex",
            name="index_collection_id_btree",
        ),
    ]
