# Generated by Django 6.1 on 2026-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PushedKey",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("sha256", models.CharField(max_length=64)),
                ("version", models.TextField()),
            ],
        ),
    ]
